# This is a basic workflow to help you get started with Actions

name: super linter 
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
 
  build:
 
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Super-Linter 
      - uses: github/super-linter@v3.13.5

